import Head from 'next/head'
import Image from 'next/image'
import Cards from '../components/Cards'
import Extra from '../components/Extra'
import Hero from '../components/Hero'
import Maps from '../components/Maps'
import WeProvide from '../components/WeProvide'
export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <Extra />
      <WeProvide />
      
      <Maps />
    </div>
  )
}
